extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.websiteurl:
              label: NIGHT_RULES.ADMIN.WEBSITE_URL
              type: text
              style: vertical
              ordering@: header.title
            header.websitetext:
              label: NIGHT_RULES.ADMIN.WEBSITE_TEXT
              type: text
              style: vertical
              ordering@: header.websiteurl

            header.authors:
              label: NIGHT_RULES.ADMIN.AUTHORS
              type: list
              fields:
                .name:
                  type: text
                  label: PLUGIN_ADMIN.NAME
                .website:
                  type: text
                  label: PLUGIN_ADMIN.SITE

            header.contributors:
              label: NIGHT_RULES.ADMIN.CONTRIBUTORS
              type: list
              fields:
                .name:
                  type: text
                  label: PLUGIN_ADMIN.NAME
                .website:
                  type: text
                  label: PLUGIN_ADMIN.SITE
