extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.visible:
              type: toggle
              label: PLUGIN_ADMIN.VISIBLE
              help: PLUGIN_ADMIN.VISIBLE_HELP
              highlight: 1
              default: 0
              options:
                1: PLUGIN_ADMIN.ENABLED
                0: PLUGIN_ADMIN.DISABLED
              validate:
                type: bool
              ordering@: 1
            header.websiteurl:
              label: NIGHT_RULES.ADMIN.WEBSITE_URL
              type: text
              style: vertical
              ordering@: header.title
            header.websitetext:
              label: NIGHT_RULES.ADMIN.WEBSITE_TEXT
              type: text
              style: vertical
              ordering@: header.websiteurl

            header.authors:
              label: NIGHT_RULES.ADMIN.AUTHORS
              type: list
              fields:
                .name:
                  type: text
                  label: PLUGIN_ADMIN.NAME
                .website:
                  type: text
                  label: PLUGIN_ADMIN.SITE

            header.contributors:
              label: NIGHT_RULES.ADMIN.CONTRIBUTORS
              type: list
              fields:
                .name:
                  type: text
                  label: PLUGIN_ADMIN.NAME
                .website:
                  type: text
                  label: PLUGIN_ADMIN.SITE
            header.image:
              label: image réseaux sociaux
              type: filepicker
              folder: '@self'
              preview_images: true
              style: vertical
            header.metadata:
              toggleable: true
              type: array
              label: PLUGIN_ADMIN.METADATA
              help: PLUGIN_ADMIN.METADATA_HELP
              placeholder_key: PLUGIN_ADMIN.METADATA_KEY
              placeholder_value: PLUGIN_ADMIN.METADATA_VALUE
        advanced:
          fields:
            overrides:
              fields:
                header.visible:
                  unset@: true
